#!/usr/bin/env python3
"""
Write trmnl/settings.yml from the pool.

The country list is not something we can hard-code: it is whatever the
archives turned out to hold, and it moves when the pool is refreshed. So
the monthly job regenerates the settings file, and the only manual step
is pasting it back into the plugin's Markup editor when the list has
changed enough to matter.

The place axis is regions, not countries. Countries were tried: outside
the United States, France and Italy the counts fall away fast, and
crossing them with two orientations and five eras leaves most of them
unable to fill a year. A selector offering Japan that then shows the
same eleven cards every other month is worse than one offering Asia
that always has something.

All three settings are multi-selects, and all three mean "everything"
when left empty. One rule, no invalid state.
"""

import json
import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from daily import ERAS, ORIENTATIONS, load_pool, regions_in  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "trmnl", "settings.yml")

POLLING_URL = ("https://raw.githubusercontent.com/nikokoren/"
               "postcard_of_the_day/main/today.json")

HEADER = """---
# Postcard of the Day -- TRMNL plugin settings
#
# Generated by make_settings.py from pool.json. The country list tracks
# whatever the archives actually hold, so it changes when the pool is
# refreshed; regenerate rather than editing by hand.
#
# Nothing selected on any of the three axes means the full catalogue.
# That is deliberate and the recipe depends on it: a reader who never
# opens the settings panel still gets a postcard every morning.

name: Postcard of the Day
refresh_interval: 60
strategy: polling
polling_verb: get
polling_url: {url}
dark_mode: "no"
no_screen_padding: "no"
"""

FIELD_HEAD = """
custom_fields:
"""


def option_block(label, keyname, help_text, options, multiple=True):
    lines = [
        "  - keyname: {}".format(keyname),
        "    field_type: select",
        "    name: {}".format(label),
        "    description: {}".format(help_text),
        "    optional: true",
    ]
    if multiple:
        lines.append("    multiple: true")
    lines.append("    options:")
    lines.extend("      - {}".format(text) for text in options)
    return "\n".join(lines) + "\n"


# TRMNL has a real boolean field. These were selects offering "true"
# and "false", which renders as a dropdown containing the word "true" --
# ugly, slow to test, and carrying a latent bug: the options parsed as
# YAML booleans while the default was a quoted string, which is exactly
# the mismatch TRMNL's own docs warn about.
#
# The map recipe has used booleans from the start and reads them with
# the same string comparison the markup here does, so this is a proven
# shape rather than a hopeful one: a TRMNL boolean reaches Liquid as the
# STRING "true" or "false". It declares no default, though; the default
# below is what the docs prescribe and makes the panel show the state
# the markup will actually render. If the editor ever disagrees, that
# line is the first thing to drop.
def toggle_block(label, keyname, description, default, help_text=None):
    block = (
        "  - keyname: {}\n"
        "    field_type: boolean\n"
        "    name: {}\n"
        "    description: {}\n"
        "    optional: true\n"
        "    default: {}\n"
    ).format(keyname, label, description, "true" if default else "false")
    if help_text:
        block += "    help_text: >-\n"
        block += textwrap.fill(help_text, width=68,
                               initial_indent="      ",
                               subsequent_indent="      ") + "\n"
    return block


# The pitch, not the catalogue entry. Somebody scrolling a plugin list
# wants to know what it feels like to have this on the wall, and the
# numbers are there to make the promise credible rather than to be the
# promise. Counts come from the pool so they never go stale.
AUTHOR_BIO = """\
  - keyname: about
    name: About This Plugin
    category: education,discovery
    field_type: author_bio
    description: >-
      Miss getting postcards in the mail? This recipe has you covered. A
      unique historical postcard from across the globe, each and every day
      -- and unlike your friends and family, it lets you choose where they
      come from. <br><br> Real printed cards from the
      public archives -- the kind somebody bought at a station kiosk, wrote
      three lines on, and posted. {pool:,} of them so far, spanning
      {countries} countries and the years {first} to {last}, held by the
      Library of Congress, the Rijksmuseum, the University of Graz and
      more. Each one arrives with whatever the catalogue knows: what it
      shows, where, who printed it, and when. <br><br> Sort by orientation, region or era -- or change
      nothing and take the whole world as it comes. No card repeats until
      every one of them has had its day. <br><br> Public domain and openly
      licensed material only. Install (don't Fork!) to receive future
      updates.
    email_address: isarworks@gmail.com
"""


def main():
    entries = load_pool()
    regions = regions_in(entries)

    body = [HEADER.format(url=POLLING_URL), FIELD_HEAD]
    body.append(option_block(
        "Orientation", "orientation",
        "Leave empty for both. Pick one to see only cards that way up.",
        [label for _, label in ORIENTATIONS]))
    # A TRMNL select has no group headings, so the two kinds are told
    # apart by order and by a marker: regions come first, and a country
    # is indented under nothing in particular but reads as narrower.
    body.append(option_block(
        "Region", "region",
        "Leave empty for everywhere. Pick several and they take turns.",
        [label for _, label, _ in regions]))
    body.append(option_block(
        "Era", "era",
        "When it was printed. Leave empty for every era.",
        [label for _, label, _, _ in ERAS]))
    body.append(toggle_block(
        "Show the caption", "show_caption",
        "The card's own title, and its date.", True))
    # This one took a marketplace reviewer a while to work out, and the
    # reason is that it does not add or remove a line: it changes one
    # that is there either way, from "1908" to "United States - 1908".
    # So the help text shows the change rather than describing it, and
    # says outright that a tenth of the pool has no place at all, where
    # the toggle does nothing whatsoever.
    body.append(toggle_block(
        "Show the place", "show_place",
        "Adds where the card is from to the line under the title.", True,
        help_text=(
            "Turns <em>1908</em> into <em>United States &middot; 1908</em>. "
            "How much detail depends on the archive -- some cards name a "
            "street, most know only a country, and some know nothing and "
            "stay as they are.")))
    body.append(toggle_block(
        "Show the credit", "show_credit",
        "The holding archive and collection.", False))
    countries = len({e["c"] for e in entries if e.get("c")})
    years = [e["y"] for e in entries]
    body.append(AUTHOR_BIO.format(
        pool=len(entries), countries=countries,
        first=min(years), last=max(years)))

    with open(OUT, "w") as fh:
        fh.write("".join(body))
    sys.stderr.write("{}: {} regions, {} eras\n".format(
        os.path.relpath(OUT, HERE), len(regions), len(ERAS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
