#!/usr/bin/env python3
"""
Write trmnl/settings.yml from the pool.

The country list is not something we can hard-code: it is whatever the
archives turned out to hold, and it moves when the pool is refreshed. So
the monthly job regenerates the settings file, and the only manual step
is pasting it back into the plugin's Markup editor when the list has
changed enough to matter.

The list is regions first, then countries. Only countries with enough
cards to fill a year on their own are offered -- see COUNTRY_MIN in
daily.py -- because offering a country with eleven postcards behind it
is promising something the recipe cannot keep. Regions are what make
the axis usable anyway: outside the United States, France and Italy the
country counts fall away fast, and faster once orientation and era cut
across them.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from daily import (ERAS, ORIENTATIONS, REGION_SLUGS,  # noqa: E402
                   countries_in, load_pool, places_in, regions_in)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "trmnl", "settings.yml")

POLLING_URL = ("https://raw.githubusercontent.com/nikokoren/"
               "postcard_of_the_day/main/today.json")

HEADER = """---
# Postcard of the Day -- TRMNL plugin settings
#
# Generated by make_settings.py from pool.json. The country list tracks
# whatever the archives actually hold, so it changes when the pool is
# refreshed; regenerate rather than editing by hand.
#
# Nothing selected on any of the three axes means the full catalogue.
# That is deliberate and the recipe depends on it: a reader who never
# opens the settings panel still gets a postcard every morning.

name: Postcard of the Day
refresh_interval: 60
strategy: polling
polling_verb: get
polling_url: {url}
dark_mode: "no"
no_screen_padding: "no"
"""

FIELD_HEAD = """
custom_fields:
"""


def option_block(label, keyname, help_text, options, multiple=True):
    lines = [
        "  - keyname: {}".format(keyname),
        "    field_type: select",
        "    name: {}".format(label),
        "    description: {}".format(help_text),
        "    optional: true",
    ]
    if multiple:
        lines.append("    multiple: true")
    lines.append("    options:")
    lines.extend("      - {}".format(text) for text in options)
    return "\n".join(lines) + "\n"


def toggle_block(label, keyname, help_text, default):
    return (
        "  - keyname: {}\n"
        "    field_type: select\n"
        "    name: {}\n"
        "    description: {}\n"
        "    optional: true\n"
        "    default: \"{}\"\n"
        "    options:\n"
        "      - true\n"
        "      - false\n"
    ).format(keyname, label, help_text, default)


AUTHOR_BIO = """
author_bio: >-
  A postcard a day from the public archives -- a real printed card, the
  kind somebody bought at a station kiosk, wrote three lines on and
  posted. Every morning the recipe picks one from about {pool:,} of them,
  drawn from the Library of Congress and Digital Commonwealth, and shows
  it with whatever the catalogue knows: what it shows, where, who
  printed it and when. Sort by orientation, place or era -- a whole
  region or one country -- or leave the settings alone and take the
  catalogue as it comes. Nothing
  repeats until every card has had its day. Public domain and openly
  licensed material only.
"""


def main():
    entries = load_pool()
    regions = regions_in(entries)
    countries = countries_in(entries)
    places = places_in(entries)

    body = [HEADER.format(url=POLLING_URL), FIELD_HEAD]
    body.append(option_block(
        "Orientation", "orientation",
        "Leave empty for both.",
        [label for _, label in ORIENTATIONS]))
    # A TRMNL select has no group headings, so the two kinds are told
    # apart by order and by a marker: regions come first, and a country
    # is indented under nothing in particular but reads as narrower.
    body.append(option_block(
        "Place", "place",
        "Regions first, then individual countries. "
        "Leave empty for everywhere.",
        [label for _, label, _ in places]))
    body.append(option_block(
        "Era", "era",
        "When it was printed. Leave empty for every era.",
        [label for _, label, _, _ in ERAS]))
    body.append(toggle_block(
        "Show the caption", "show_caption",
        "The card's own title, and its date.", "true"))
    body.append(toggle_block(
        "Show the place", "show_place",
        "Where the card is from, under the title.", "true"))
    body.append(toggle_block(
        "Show the credit", "show_credit",
        "The holding archive and collection.", "false"))
    body.append(AUTHOR_BIO.format(pool=len(entries)))

    with open(OUT, "w") as fh:
        fh.write("".join(body))
    sys.stderr.write("{}: {} regions, {} countries, {} eras\n".format(
        os.path.relpath(OUT, HERE), len(regions), len(countries), len(ERAS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
